name: Install package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pkg-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Create package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py sdist
  pkg-install:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Install | Uninstall package - archive
        working-directory: dist
        run: |
          pip install *.tar.gz
          python -c "import torch_emd"
          pip uninstall -y torch_emd
      - name: Install | Uninstall package - wheel
        working-directory: dist
        run: |
          pip install *.whl
          python -c "import torch_emd"
          pip uninstall -y torch_emd
